# Generated by Django 3.2.9 on 2021-11-30 14:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('hospitalname', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=100)),
                ('charge', models.PositiveIntegerField()),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=100)),
                ('Password', models.CharField(max_length=50)),
                ('BirthDate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('expiryDate', models.DateTimeField(default=datetime.datetime(2021, 12, 30, 20, 2, 47, 95569))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='WebApp.patient')),
            ],
        ),
    ]
