# Generated by Django 3.2.9 on 2021-11-30 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienttoken',
            name='expiryDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 30, 20, 2, 55, 956630)),
        ),
    ]
