# Generated by Django 3.2.9 on 2021-11-30 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0015_alter_patienttoken_expirydate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patienttoken',
            name='expiryDate',
        ),
    ]
