# Generated by Django 3.2.9 on 2021-11-30 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0019_alter_patienttoken_expirydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienttoken',
            name='expirydate',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 30, 21, 37, 10, 167178)),
        ),
    ]
