# Generated by Django 3.2.9 on 2021-11-30 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0021_alter_patienttoken_expirydate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patienttoken',
            name='expirydate',
        ),
        migrations.AddField(
            model_name='patienttoken',
            name='exdate',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 30, 21, 37, 22, 551007)),
        ),
    ]
