# Generated by Django 3.2.9 on 2021-11-30 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0022_auto_20211130_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienttoken',
            name='exdate',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 30, 21, 37, 24, 561198)),
        ),
    ]
