# Generated by Django 3.2.9 on 2021-12-02 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0040_alter_patienttoken_exdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctorname',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[\\w#\\-_\\+\\.\\(\\)@~\\\\/*!&]+$', message='Contains some prohibited symbols')]),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(max_length=100, validators=[django.core.validators.RegexValidator('^[\\w#\\-_\\+\\.\\(\\)@~\\\\/*!&]+$', message='Contains some prohibited symbols')]),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='hospitalname',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[\\w#\\-_\\+\\.\\(\\)@~\\\\/*!&]+$', message='Contains some prohibited symbols')]),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='password',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[\\w#\\-_\\+\\.\\(\\)@~\\\\/*!&]+$', message='Contains some prohibited symbols')]),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[\\w#\\-_\\+\\.\\(\\)@~\\\\/*!&]+$', message='Contains some prohibited symbols')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Password',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[\\w#\\-_\\+\\.\\(\\)@~\\\\/*!&]+$', message='Contains some prohibited symbols')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Username',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[\\w#\\-_\\+\\.\\(\\)@~\\\\/*!&]+$', message='Contains some prohibited symbols')]),
        ),
    ]
