# Generated by Django 3.2.9 on 2021-12-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0042_alter_doctor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
